spring:
  application:
    name: data
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties.hibernate.default_schema: test
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/BED_CTBP
    username: postgres
    password: toledo   
    
server:
  port: 9333
  
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka